<?php

namespace Database\Seeders;

/**
 * Default positions grouped by category (slug keys match PositionCategory enum values).
 *
 * @return array<string, list<string>>
 */
final class PositionCatalog
{
    public static function grouped(): array
    {
        return [
            'production' => [
                'Director',
                'Film Director',
                'Assistant Director',
                '1st Assistant Director',
                '2nd Assistant Director',
                'Producer',
                'Executive Producer',
                'Associate Producer',
                'Line Producer',
                'Production Manager',
                'Production Coordinator',
                'Location Manager',
                'Casting Director',
                'Casting Assistant',
                'Script Supervisor',
                'Production Assistant',
                'Runner',
                'Fixer',
            ],
            'camera_lighting' => [
                'Director of Photography',
                'Cinematographer',
                'Camera Operator',
                '1st AC',
                '2nd AC',
                'Focus Puller',
                'DIT',
                'Drone Operator',
                'Steadicam Operator',
                'Gimbal Operator',
                'Photographer',
                'Behind The Scenes Photographer',
                'Gaffer',
                'Best Boy',
                'Electrician',
                'Key Grip',
                'Grip',
            ],
            'art_styling' => [
                'Art Director',
                'Production Designer',
                'Set Designer',
                'Set Decorator',
                'Props Master',
                'Stylist',
                'Wardrobe Stylist',
                'Costume Designer',
                'Makeup Artist',
                'Hair Stylist',
                'Food Stylist',
            ],
            'post_production' => [
                'Post-Production Supervisor',
                'Post-Production Producer',
                'Offline Editor',
                'Online Editor',
                'Editor',
                'Senior Editor',
                'Assistant Editor',
                'Colorist',
                'Color Grading Artist',
                'VFX Supervisor',
                'VFX Artist',
                'Compositor',
                'Rotoscope Artist',
                'Cleanup Artist',
                'Motion Designer',
                'Motion Graphics Artist',
                'Animator',
                '2D Animator',
                '3D Animator',
                'CG Artist',
                '3D Artist',
                'CGI Artist',
                'Storyboard Artist',
                'Sound Designer',
                'Audio Engineer',
                'Sound Mixer',
                'Music Producer',
                'Composer',
                'Voice Over Artist',
                'Dubbing Artist',
                'Subtitling',
                'Transcriber',
            ],
            'agency_creative' => [
                'Creative Director',
                'Associate Creative Director',
                'Copywriter',
                'Senior Copywriter',
                'Creative Strategist',
                'Brand Strategist',
                'Strategy Director',
                'Account Director',
                'Account Manager',
                'Client Servicing',
                'Project Manager',
                'Traffic Manager',
                'Graphic Designer',
                'Senior Graphic Designer',
                'Visual Designer',
                'Illustrator',
                'Content Creator',
                'Content Writer',
                'Social Media Manager',
                'Community Manager',
                'Media Buyer',
                'Performance Marketer',
                'Digital Marketing Specialist',
                'Marketing Manager',
                'Brand Manager',
                'PR Manager',
                'Influencer Manager',
            ],
            'brand_client' => [
                'Brand Representative',
                'Marketing Director',
                'Marketing Lead',
                'Communications Manager',
                'Campaign Manager',
                'Product Manager',
                'Category Manager',
            ],
            'other' => [
                'Founder',
                'Co-Founder',
                'CEO',
                'Managing Director',
                'Consultant',
                'Special Thanks',
                'Talent',
                'Actor',
                'Actress',
                'Presenter',
                'Influencer',
                'Model',
            ],
        ];
    }
}
