deployment:
  tasks:
    - export ROOTPATH=/home/adsofiraq
    - export PUBLICPATH=/home/adsofiraq/public_html
    - /bin/cp -R app $ROOTPATH
    - /bin/cp -R bootstrap $ROOTPATH
    - /bin/cp -R config $ROOTPATH
    - /bin/cp -R database $ROOTPATH
    - /bin/cp -R resources $ROOTPATH
    - /bin/cp -R routes $ROOTPATH
    - /bin/cp -R public/* $PUBLICPATH