<?php

return [
    'site_name' => 'Ads Of Iraq',
    'site_tagline' => 'Iraqi Advertising Archive',
    'site_url' => env('APP_URL', 'https://adsofiraq.com'),

    'default_og_image' => '/web-app-manifest-512x512.png',

    'organization' => [
        'logo_path' => '/web-app-manifest-512x512.png',
        'logo_width' => 512,
        'logo_height' => 512,
        'same_as' => array_values(array_filter([
            env('SEO_FACEBOOK_URL'),
            env('SEO_INSTAGRAM_URL'),
            env('SEO_LINKEDIN_URL'),
            env('SEO_TWITTER_URL'),
            env('SEO_YOUTUBE_URL'),
        ])),
    ],

    'twitter_site' => '@adsofiraq',

    'arabic_keywords' => [
        'global' => 'اعلانات العراق، الأرشيف الإعلاني العراقي',
        'campaigns' => 'الحملات الإعلانية العراقية',
        'agencies' => 'وكالات الإعلان في العراق',
        'production_houses' => 'شركات الإنتاج في العراق',
        'brands' => 'العلامات التجارية العراقية',
        'people' => 'المبدعون في الإعلان العراقي',
        'categories' => 'حملات إعلانية حسب التصنيف',
    ],

    'listing_noindex_params' => [
        'page',
        'sort',
        'search',
        'medium',
        'country',
        'year',
        'brand',
        'agency',
        'industry',
        'q',
    ],

    'static_pages' => [
        ['route' => 'home', 'priority' => '1.0', 'changefreq' => 'daily'],
        ['route' => 'campaigns.index', 'priority' => '0.9', 'changefreq' => 'daily'],
        ['route' => 'agencies.index', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'brands.index', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'people.index', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'rankings.index', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.top-agencies', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.top-production-houses', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.most-viewed', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.trending', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.most-appreciated', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.top-directors', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.top-editors', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.top-brands', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.top-commercials', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'rankings.top-creative-directors', 'priority' => '0.7', 'changefreq' => 'weekly'],
        ['route' => 'landing.iraqi-advertising', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'landing.iraq-agencies', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'landing.iraq-production-houses', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'landing.iraq-commercials', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'landing.iraq-tv-commercials', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'landing.iraq-creative-industry', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'made-by-iraq.index', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'featured.index', 'priority' => '0.8', 'changefreq' => 'weekly'],
        ['route' => 'awards.index', 'priority' => '0.7', 'changefreq' => 'monthly'],
        ['route' => 'pages.about', 'priority' => '0.6', 'changefreq' => 'monthly'],
        ['route' => 'pages.contact', 'priority' => '0.5', 'changefreq' => 'monthly'],
        ['route' => 'pages.help', 'priority' => '0.5', 'changefreq' => 'monthly'],
        ['route' => 'pages.submit-advertise', 'priority' => '0.6', 'changefreq' => 'monthly'],
        ['route' => 'pages.terms-policies', 'priority' => '0.4', 'changefreq' => 'yearly'],
        ['route' => 'pages.editorial-standards', 'priority' => '0.5', 'changefreq' => 'yearly'],
    ],

    'sitemaps' => [
        'campaigns' => 'sitemap-campaigns.xml',
        'agencies' => 'sitemap-agencies.xml',
        'production_houses' => 'sitemap-production-houses.xml',
        'brands' => 'sitemap-brands.xml',
        'people' => 'sitemap-people.xml',
        'categories' => 'sitemap-categories.xml',
        'tags' => 'sitemap-tags.xml',
        'rankings' => 'sitemap-rankings.xml',
        'landing_pages' => 'sitemap-landing-pages.xml',
        'pages' => 'sitemap-pages.xml',
    ],

    'favicon_urls' => [
        '/favicon.ico',
        '/favicon-16x16.png',
        '/favicon-32x32.png',
        '/favicon-96x96.png',
        '/apple-touch-icon.png',
        '/site.webmanifest',
    ],
];
